package org.jagodzinskikacper.renataslibrary.book;

public enum Category {
    BIOGRAFIA, BIZNES, DZIECIECA, MŁODZIEŻOWA, FANTASY, HISTORYCZNA, HORROR, INFORMATYKA, KOMIKS, KRYMINAŁ, THRILLER, KUCHENNA, OBYCZAJOWA, NAUKOWA, LITERATURA_PIĘKNA, PODRĘCZNIK, POEZJA, PORADNIK, PRAWO, RELIGIA, ROZWÓJ, SCI_FI, SPORT, SZTUKA, TURYSTYKA, ZDROWIE;
}
